### ISSUE TITLE
Release an updated `docker-java`

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docker-java#6]
Hey,

docker-java was released with some changes that will make a test in `wedeploy/images` pass - https://github.com/testcontainers/testcontainers-java/issues/293#issuecomment-312293768 

It'd be great to have those changes in `wedeploy/docker-java` 👍  

Could you take a look at it @igr ?

Thx!

**Comment by igr** [comment]
It seems docker-java fixed all our issues.

**Comment by igr** [comment]
https://github.com/wedeploy/conqueror/pull/523
